Repository theforeman/smart_proxy_dynflow, pull requests merged in 2021-06, with the labels that each got.

#78 Merge smart_proxy_dynflow_core and smart_proxy_dynflow
  Rakefile
  bin/smart_proxy_dynflow_core
  config/settings.yml.example
  deploy/smart_proxy_dynflow_core.init
  deploy/smart_proxy_dynflow_core.service
  lib/smart_proxy_dynflow.rb
  lib/smart_proxy_dynflow/api.rb
  lib/smart_proxy_dynflow/callback.rb
  lib/smart_proxy_dynflow/core.rb
  lib/smart_proxy_dynflow/helpers.rb
  lib/smart_proxy_dynflow/http_config.ru
  lib/smart_proxy_dynflow/log.rb
  lib/smart_proxy_dynflow/middleware/keep_current_request_id.rb
  lib/smart_proxy_dynflow/plugin.rb
  lib/smart_proxy_dynflow/settings.rb
  lib/smart_proxy_dynflow/task_launcher_registry.rb
  lib/smart_proxy_dynflow/testing.rb
  lib/smart_proxy_dynflow_core.rb
  lib/smart_proxy_dynflow_core/api.rb
  lib/smart_proxy_dynflow_core/bundler_helper.rb
  lib/smart_proxy_dynflow_core/callback.rb
  lib/smart_proxy_dynflow_core/helpers.rb
  lib/smart_proxy_dynflow_core/launcher.rb
  lib/smart_proxy_dynflow_core/log.rb
  lib/smart_proxy_dynflow_core/logger_middleware.rb
  lib/smart_proxy_dynflow_core/request_id_middleware.rb
  lib/smart_proxy_dynflow_core/settings.rb
  lib/smart_proxy_dynflow_core/task_launcher_registry.rb
  lib/smart_proxy_dynflow_core/testing.rb
  settings.d/dynflow.yml.example
  smart_proxy_dynflow_core.gemspec
  test/api_test.rb
  test/api_test/api_test.rb
  test/callback_test.rb
  test/core_test/callback_test.rb
  test/core_test/test_helper.rb
  test/helpers_test.rb
  test/task_launcher_registry_test.rb
  test/test_helper.rb
Labels: Needs testing, Waiting on contributor

#81 Import foreman_tasks_core
  lib/smart_proxy_dynflow.rb
  lib/smart_proxy_dynflow/action.rb
  lib/smart_proxy_dynflow/action/batch.rb
  lib/smart_proxy_dynflow/action/batch_callback.rb
  lib/smart_proxy_dynflow/action/batch_runner.rb
  lib/smart_proxy_dynflow/action/output_collector.rb
  lib/smart_proxy_dynflow/action/runner.rb
  lib/smart_proxy_dynflow/action/shareable.rb
  lib/smart_proxy_dynflow/action/single_runner_batch.rb
  lib/smart_proxy_dynflow/api.rb
  lib/smart_proxy_dynflow/callback.rb
  lib/smart_proxy_dynflow/continuous_output.rb
  lib/smart_proxy_dynflow/core.rb
  lib/smart_proxy_dynflow/helpers.rb
  lib/smart_proxy_dynflow/log.rb
  lib/smart_proxy_dynflow/otp_manager.rb
  lib/smart_proxy_dynflow/plugin.rb
  lib/smart_proxy_dynflow/proxy_adapter.rb
  lib/smart_proxy_dynflow/runner.rb
  lib/smart_proxy_dynflow/runner/base.rb
  lib/smart_proxy_dynflow/runner/command.rb
  lib/smart_proxy_dynflow/runner/command_runner.rb
  lib/smart_proxy_dynflow/runner/dispatcher.rb
  lib/smart_proxy_dynflow/runner/parent.rb
  lib/smart_proxy_dynflow/runner/update.rb
  lib/smart_proxy_dynflow/settings.rb
  lib/smart_proxy_dynflow/settings_loader.rb
  lib/smart_proxy_dynflow/task_launcher.rb
  lib/smart_proxy_dynflow/task_launcher/abstract.rb
  lib/smart_proxy_dynflow/task_launcher/batch.rb
  lib/smart_proxy_dynflow/task_launcher/group.rb
  lib/smart_proxy_dynflow/task_launcher/single.rb
  lib/smart_proxy_dynflow/task_launcher_registry.rb
  lib/smart_proxy_dynflow/testing.rb
  lib/smart_proxy_dynflow/ticker.rb
  lib/smart_proxy_dynflow/version.rb
  test/api_test.rb
  test/callback_test.rb
  test/dispatcher_test.rb
  test/helpers_test.rb
  test/otp_manager_test.rb
  test/runner_test.rb
  test/task_launcher_test.rb
Labels: Needs testing

#82 Fixes #32811 - Unify bundler*.d directories
  Gemfile
  bundler.d/dynflow.rb
  smart_proxy_dynflow.gemspec
Labels: Needs testing, Not yet reviewed

#83 Refs #32534 - add forgotten deps from dynflow_core
  smart_proxy_dynflow.gemspec
Labels: Needs testing

#84 Fix OutputCollector superclass
  lib/smart_proxy_dynflow/action/output_collector.rb
Labels: Needs testing

#86 Refs #32534 - dont use SmartProxyDynflowCore
  lib/smart_proxy_dynflow/action/batch_callback.rb
  lib/smart_proxy_dynflow/action/batch_runner.rb
  lib/smart_proxy_dynflow/action/shareable.rb
Labels: Needs testing, Not yet reviewed

#85 Require smart_proxy_dynflow by smart_proxy_dynflow_core
  smart_proxy_dynflow_core.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#87 Drop smart_proxy_dynflow_core deps, add constraint on sp_dynflow
  smart_proxy_dynflow_core.gemspec
Labels: Needs testing, Waiting on contributor
